### ISSUE TITLE
Find typo in Program Macro tab

### ISSUE THREAD

**Issue by kame404** [brainmagi/Orbital2Core#3]
プログラムマクロを設定する画面にて、誤植と思われるものを見つけたので報告いたします。
Version: 1.5.5
Language: English

`Program Marco -> Program Macro`

**Comment by bm-kenji-nakamura** [comment]
@kame404 ご報告ありがとうございます！対応いたします！

**Comment by bm-kenji-nakamura** [comment]
Fixed v1.5.7
